CREATE USER data_dwh WITH PASSWORD 'data_dwh';

CREATE SCHEMA staging AUTHORIZATION data_dwh;
CREATE SCHEMA ods AUTHORIZATION data_dwh;
CREATE SCHEMA dw AUTHORIZATION data_dwh;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA staging
GRANT ALL PRIVILEGES ON TABLES TO data_dwh;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ods
GRANT ALL PRIVILEGES ON TABLES TO data_dwh;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA dw
GRANT ALL PRIVILEGES ON TABLES TO data_dwh;